name: Build Windows EXE (RTSP4CamRecorder)
on:
  workflow_dispatch:
  push:
    paths:
      - 'rtsp_4ch_recorder.py'      # ←実ファイル名に合わせて変更可
      - 'requirements.txt'
      - '.github/workflows/windows-build.yml'

jobs:
  build:
    runs-on: windows-latest
    env:
      APP_PY: rtsp_4ch_recorder.py   # ←ここも実ファイル名に合わせる

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install ffmpeg and bundle into bin
        shell: pwsh
        run: |
          choco install ffmpeg -y
          $ff = Join-Path $env:ChocolateyInstall 'bin/ffmpeg.exe'
          if (!(Test-Path $ff)) { throw "ffmpeg not found at $ff" }
          New-Item -ItemType Directory -Force -Path bin | Out-Null
          Copy-Item $ff bin\ffmpeg.exe -Force

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --clean ^
            --name RTSP4CamRecorder ^
            --windowed ^
            --collect-all PySide6 ^
            --collect-all cv2 ^
            --add-data "bin;bin" ^
            "%APP_PY%"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RTSP4CamRecorder-win
          path: dist/RTSP4CamRecorder/
